### ISSUE TITLE
Error with render function.

### ISSUE THREAD

**Issue by dfrownfelter** [firsttimersonly/pug#2]
There's an error when running the test suite. Follow the guide to get started. Install dependencies and run `npm test` to start finding the error.

**Comment by miarkus** [comment]
you mind me taking it?

**Comment by dfrownfelter** [comment]
Go for it! Your the first one, I'll asign it to you.

**Comment by miarkus** [comment]
Sorry, should I wait for you to assign me?

**Comment by dfrownfelter** [comment]
No that was my mistake, I don't think I can physically assign it to you. But since you commented on it, I won't accept any pull requests on the issue from any other people. So it's yours.

**Comment by dfrownfelter** [comment]
Let me know if you have any more questions

**Comment by miarkus** [comment]
I've submitted my very first PR #3 Please take a look and let me know if it's any good.
